"""Initial migration.

Revision ID: f4c4527f8d69
Revises: 030112f1ee91
Create Date: 2024-09-08 18:03:27.402890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c4527f8d69'
down_revision = '030112f1ee91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settleup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=False))
        batch_op.drop_column('amount_to')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settleup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_to', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
